language: c

addons:
  apt_packages:
    - libgmp-dev
    - libgmp-dev:i386
    - libreadline-dev
    - libreadline-dev:i386
    - zlib1g-dev
    - zlib1g-dev:i386
    - gcc-multilib
    - g++-multilib

matrix:
  include:
    - env: CC=clang CXX=clang++
      compiler: clang
    - env:
      compiler: gcc
    - env: ABI=32

branches:
  only:
    - master

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
