name: cohomolo
version: 1.6.11
date: 2023-01-03
description: |
    Cohomology groups of finite groups on finite modules

authors:
    - name: Derek Holt
      url: http://homepages.warwick.ac.uk/staff/D.F.Holt/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.7"

www: https://gap-packages.github.io/cohomolo
readme: README.md
packageinfo: https://gap-packages.github.io/cohomolo/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/cohomolo/releases/download/v1.6.11/cohomolo-1.6.11.tar.gz

abstract: |
    The <span class="pkgname">cohomolo</span> package is a       <span class="pkgname">GAP</span> interface to some `C' programs   for computing Schur multipliers and covering groups of finite groups   and first and second cohomology groups of finite groups acting   on finite modules

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
