name: cohomolo
version: "1.6.12"
license: "GPL-2.0-or-later"
date: 2025-10-17
description: |
    Cohomology groups of finite groups on finite modules

authors:
    - name: Derek Holt
      url: http://homepages.warwick.ac.uk/staff/D.F.Holt/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.7"

www: https://gap-packages.github.io/cohomolo
readme: README.md
packageinfo: https://gap-packages.github.io/cohomolo/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/cohomolo/releases/download/v1.6.12/cohomolo-1.6.12.tar.gz

abstract: |
    The <span class="pkgname">cohomolo</span> package is a       <span class="pkgname">GAP</span> interface to some `C' programs   for computing Schur multipliers and covering groups of finite groups   and first and second cohomology groups of finite groups acting   on finite modules

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    Cohomology, Schur Multiplier, Covering group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HT25</span>]   <b class='BibAuthor'>Holt, D. and GAP Team, T.</b>,
     <i class='BibTitle'>cohomolo, Cohomology groups of finite groups on finite modules,
             Version 1.6.12</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/cohomolo">https://gap-packages.github.io/cohomolo</a></span>.
    </p>
    

bibtex: |
    @misc{ cohomolo,
      author =           {Holt, D. and GAP Team, T.},
      title =            {{cohomolo},  {Cohomology  groups  of  finite groups on
                          finite modules}, {V}ersion 1.6.12},
      month =            {Oct},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/cohomolo}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{cohomolo}}},
      keywords =         {Cohomology; Schur Multiplier; Covering group},
      printedkey =       {HT25}
    }

