# cohomolo, chapter 1
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("cohomolo01.tst");

# doc/cohomolo.xml:126-134
gap> G:= AlternatingGroup( 5 );
Alt( [ 1 .. 5 ] )
gap> F:= Image( IsomorphismFpGroupByGenerators( G, GeneratorsOfGroup(G) ) );
<fp group of size 60 on the generators [ F1, F2 ]>
gap> C:= CHR( G, 2, F );;
gap> CoveringGroup( C );
<fp group of size 120 on the generators [ f1, f2, f3 ]>

# doc/cohomolo.xml:184-193
gap> G:= Group( [ (1,2), (3,4) ] );;
gap> F:= Image( IsomorphismFpGroupByGenerators( G, GeneratorsOfGroup(G) ) );
<fp group of size 4 on the generators [ F1, F2 ]>
gap> C:= CHR( G, 2, F, [ [[1]], [[1]] ] * Z(2) );;
gap> ext:= SplitExtensionCHR( C );
<fp group of size 8 on the generators [ f1, f2, f3 ]>
gap> StructureDescription( ext );
"C2 x C2 x C2"

# doc/cohomolo.xml:238-254
gap> G:= ElementaryAbelianGroup( IsPermGroup, 4 );
Group([ (1,2), (3,4) ])
gap> F:= Image( IsomorphismFpGroupByGenerators( G, GeneratorsOfGroup(G) ) );
<fp group of size 4 on the generators [ F1, F2 ]>
gap> C:= CHR( G, 2, F, [ [[1]], [[1]] ] * Z(2) );;
gap> SecondCohomologyDimension( C );
3
gap> ext:= NonsplitExtension( C, [ 1, 0, 0 ] );
<fp group of size 8 on the generators [ f1, f2, f3 ]>
gap> StructureDescription( ext );
"D8"
gap> ext:= NonsplitExtension( C, [ 1, 1, 1 ] );
<fp group of size 8 on the generators [ f1, f2, f3 ]>
gap> StructureDescription( ext );
"Q8"

#
gap> STOP_TEST("cohomolo01.tst", 1);
